#!/system/bin/sh
MODDIR=${0%/*}

# Cache Cleaner (clear cache of all apps by typing `su -c cleaner` in Terminal)
clear

echo "Cache+ (Magisk Module)"
sleep 1
echo "- A module that allows your device"
echo "- To clear cache of all apps on every boot."
echo ""
sleep 1
echo "- And you can manually clear cache"
echo "- By typing 'su -c cleaner' in Terminal."
echo ""
sleep 1

[ ! "$(whoami)" == "root" ] && echo "! Error..." && echo "! Run as root user only." && exit 1

echo "Do you want to clear cache of all apps? <yes/no>"
printf "Your choice: "
read choice
if [ "$choice" == "yes" ]; then
    find /data/data/*/cache/* -delete &>/dev/null
    find /sdcard/Android/data/*/cache/* -delete &>/dev/null
    sleep 0.7
    echo ""
    echo "Done, all caches have been cleared!"
fi
